overrides:
  "@antfu/eslint-config>@eslint/markdown": "-"
  "@antfu/eslint-config>@stylistic/eslint-plugin": "-"
  "@antfu/eslint-config>eslint-plugin-jsonc": "-"
  "@antfu/eslint-config>eslint-plugin-toml": "-"
  "@antfu/eslint-config>eslint-plugin-vue": "-"
  "@antfu/eslint-config>eslint-processor-vue-blocks": "-"
  "@antfu/eslint-config>jsonc-eslint-parser": "-"
  "@antfu/eslint-config>toml-eslint-parser": "-"
  "@antfu/eslint-config>vitest": "-"
  "@antfu/eslint-config>vue-eslint-parser": "-"
  array-includes: npm:@nolyfill/array-includes@^1
  array.prototype.flat: npm:@nolyfill/array.prototype.flat@^1
  eslint-plugin-pnpm>jsonc-eslint-parser: "-"
  is-core-module: npm:@nolyfill/is-core-module@^1
  object.assign: npm:@nolyfill/object.assign@^1
  object.values: npm:@nolyfill/object.values@^1

enableGlobalVirtualStore: false
savePrefix: ""
shellEmulator: true
